# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ip_to_address_pb2 as ip__to__address__pb2


class IpLocationStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetLocationIp = channel.unary_unary(
        '/IpLocation/GetLocationIp',
        request_serializer=ip__to__address__pb2.Ip.SerializeToString,
        response_deserializer=ip__to__address__pb2.Ip.FromString,
        )


class IpLocationServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetLocationIp(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_IpLocationServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetLocationIp': grpc.unary_unary_rpc_method_handler(
          servicer.GetLocationIp,
          request_deserializer=ip__to__address__pb2.Ip.FromString,
          response_serializer=ip__to__address__pb2.Ip.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'IpLocation', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
